
export const FETCH_DASHBOARD_CONTENT = 'FETCH_DASHBOARD_CONTENT';
export const CLEAR_DASHBOARD_CONTENT = 'CLEAR_DASHBOARD_CONTENT';
export const SET_ALL_USER_IMAGES = 'SET_ALL_USER_IMAGES';
export const RESET_ALL_USER_IMAGES = 'RESET_ALL_USER_IMAGES';