export const SHOW_FILE_UPLOAD_SECTION = 'SHOW_FILE_UPLOAD_SECTION';
export const HIDE_FILE_UPLOAD_SECTION = 'HIDE_FILE_UPLOAD_SECTION';
export const SET_ERROR = 'SET_ERROR';
export const RESET_ERROR = 'RESET_ERROR';
export const SET_SUCCESS = 'SET_SUCCESS';
export const RESET_SUCCESS = 'RESET_SUCCESS'