export const SHOW_FILE_UPLOAD_SECTION = 'SHOW_FILE_UPLOAD_SECTION';
export const HIDE_FILE_UPLOAD_SECTION = 'HIDE_FILE_UPLOAD_SECTION';
export const SET_ERROR = 'SET_ERROR';
export const RESET_ERROR = 'RESET_ERROR';
export const SET_SUCCESS = 'SET_SUCCESS';
export const RESET_SUCCESS = 'RESET_SUCCESS'

export const SET_LOADING = 'SET_LOADING'
export const RESET_LOADING = 'RESET_LOADING'

export const SET_UPLOAD_DURATION = 'UPLOAD_DURATION';
export const RESET_UPLOAD_DURATION = 'RESET_UPLOAD_DURATION'

export const SET_UPLOAD_PROGRESS = 'SET_UPLOAD_PROGRESS';
export const RESET_UPLOAD_PROGRESS = 'RESET_UPLOAD_PROGRESS';

export const SHOW_PDF_READER = 'SHOW_PDF_READER';
export const HIDE_PDF_READER = 'HIDE_PDF_READER';

export const SET_SHOW_IMAGE_VIEWER = 'SHOW_IMAGE_VIEWER';
export const RESET_SHOW_IMAGE_VIEWER = 'HIDE_IMAGE_VIEWER';

export const SHOW_VIDEO_STREAMER = 'SHOW_VIDEO_STREAMER';
export const HIDE_VIDEO_STREAMER = 'HIDE_VIDEO_STREAMER';